### PR TITLE
Make sure bulk delete moves pages to trash can

### PR DESCRIPTION
**Pull request by rinti**
Fixes https://github.com/Frojd/wagtail-trash/issues/17

### CODE REVIEW

**Comment by rinti** [comment]
This fails the older wagtail versions where bulk actions weren't a thing. I'm wondering if we should update the test matrix to wagtail >= 3 and drop < 3 support.

**Comment by rinti** [comment]
2.15 LTS was dropped in february, so I'd say we're safe to push the test matrix

**Comment by marteinn** [comment]
+1. Let's only support the maintained Wagtail versions.

**Review by marteinn — APPROVED** [review]
LGTM!

**Pull request merged**
